# Generated by Django 3.1.4 on 2021-01-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0001_initial_squashed_0088_racialsense'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'app_label': 'dnd5e', 'model__in': ['class', 'race', 'subrace', 'background']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='feature',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adventuremonster',
            name='location_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Муж.'), (2, 'Жен.'), (3, 'Не определено')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='class',
            name='skill_proficiency_limit',
            field=models.PositiveSmallIntegerField(verbose_name='Количество мастерства в навыках'),
        ),
        migrations.AlterField(
            model_name='monsteraction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monsteraction',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='npc',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Муж.'), (2, 'Жен.'), (3, 'Не определено')]),
        ),
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.CharField(choices=[('t', 'Крошечный'), ('s', 'Маленький'), ('m', 'Средний'), ('l', 'Большой'), ('h', 'Огромный'), ('g', 'Гигантский')], max_length=1, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', related_query_name='skill', to='dnd5e.ability', verbose_name='Характеристика'),
        ),
    ]
