# Generated by Django 3.1.5 on 2021-01-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0002_auto_20210105_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='feats',
        ),
    ]
