# Generated by Django 3.1.5 on 2021-01-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0004_auto_20210106_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(editable=False, related_name='_character_languages_+', to='dnd5e.Language', verbose_name='Владение языками'),
        ),
        migrations.AlterField(
            model_name='character',
            name='features',
            field=models.ManyToManyField(editable=False, related_name='_character_features_+', to='dnd5e.Feature', verbose_name='Умения'),
        ),
    ]
