# Generated by Django 3.1.4 on 2021-01-07 21:19

from django.db import migrations, models
import dnd5e.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0006_background_known_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cost', dnd5e.models.CostField(verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
    ]
