# Generated by Django 3.1.4 on 2021-01-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0008_auto_20210108_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancmentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, verbose_name='Код')),
                ('text', models.TextField(verbose_name='Отображаемый текст')),
            ],
            options={
                'verbose_name': 'Выбор для персонажа',
                'verbose_name_plural': 'Выборы для персонажей',
                'ordering': ['code'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CharacterAdvancmentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_object_id', models.PositiveIntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', related_query_name='choice', to='dnd5e.character')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dnd5e.advancmentchoice')),
                ('reason_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Выбор персонажа',
                'verbose_name_plural': 'Выборы персонажа',
                'ordering': ['character', 'choice'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='background',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='_background_choices_+', to='dnd5e.AdvancmentChoice', verbose_name='Выборы для персонажа'),
        ),
    ]
