# Generated by Django 3.1.4 on 2021-01-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0009_auto_20210109_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Без категории'), (5, 'Инструменты ремеслиников'), (10, 'Музыкальные инструменты'), (15, 'Игровой набор')], default=0),
        ),
    ]
