# Generated by Django 3.1.4 on 2021-01-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0011_auto_20210110_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancmentchoice',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
