# Generated by Django 3.1.4 on 2021-01-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0012_advancmentchoice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Уровень')),
                ('proficiency_bonus', models.PositiveSmallIntegerField(verbose_name='Бонус мастерства')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd5e.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Таблица уровней',
                'verbose_name_plural': 'Таблицы уровней',
                'ordering': ['klass', 'level'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ClassLevelAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_object_id', models.PositiveIntegerField()),
                ('advance_content_type', models.ForeignKey(limit_choices_to={'app_label': 'dnd5e', 'model__in': ['feature', 'advancmentchoice']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='advantage', to='dnd5e.classlevels', verbose_name='Уровень класса')),
            ],
            options={
                'verbose_name': 'Преимущество уровня',
                'verbose_name_plural': 'Преимущества уровней',
                'default_permissions': (),
            },
        ),
    ]
