# Generated by Django 3.1.4 on 2021-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0013_classleveladvance_classlevels'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='group',
            field=models.CharField(blank=True, max_length=12, verbose_name='Группа умений'),
        ),
    ]
