# Generated by Django 3.1.4 on 2021-01-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0014_feature_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='features',
        ),
        migrations.AddField(
            model_name='feature',
            name='rechargeable',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не требуется'), (10, 'Короткий отдых'), (20, 'Длинный отдых')], default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='stackable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classleveladvance',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', related_query_name='advantage', to='dnd5e.classlevels', verbose_name='Уровень класса'),
        ),
        migrations.AlterField(
            model_name='classlevels',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_feats', to='dnd5e.class', verbose_name='Класс'),
        ),
        migrations.CreateModel(
            name='CharacterFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_charges', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('used', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', related_query_name='feature', to='dnd5e.character')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dnd5e.feature')),
            ],
            options={
                'verbose_name': 'Особенность персонажа',
                'verbose_name_plural': 'Особенности персонажей',
                'ordering': ['character', 'feature'],
                'default_permissions': (),
            },
        ),
    ]
