# Generated by Django 3.1.4 on 2021-01-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0015_auto_20210117_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd5e.rulebook', verbose_name='Книга правил')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd5e.class', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Архетип',
                'verbose_name_plural': 'Архетипы',
                'default_permissions': (),
            },
        ),
    ]
