# Generated by Django 3.1.4 on 2021-01-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0017_auto_20210119_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='subklass',
            new_name='subclass',
        ),
    ]
