# Generated by Django 3.1.6 on 2021-02-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0019_auto_20210119_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancmentchoice',
            name='oneshoot',
            field=models.BooleanField(default=False, verbose_name='Одноразовый выбор'),
        ),
    ]
