# Generated by Django 3.1.6 on 2021-02-21 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0020_advancmentchoice_oneshoot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classlevels',
            managers=[
                ('tables', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='source_condition',
        ),
        migrations.RemoveField(
            model_name='monsteraction',
            name='orig_name',
        ),
        migrations.RemoveField(
            model_name='monstertrait',
            name='orig_name',
        ),
        migrations.AlterField(
            model_name='feature',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'app_label': 'dnd5e', 'model__in': ['class', 'subclass', 'race', 'subrace', 'background']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='condition_immunity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Poison', 'Отравление'), ('Exhaust', 'Истощение'), ('Deafened', 'Глухота'), ('Blinded', 'Ослепление'), ('Paralyzed', 'Паралич'), ('Charmed', 'Очарование'), ('Petrified', 'Окаменение'), ('Frightened', 'Испруг')], default=None, max_length=70, null=True, verbose_name='Иммунитет к состоянию'),
        ),
    ]
