# Generated by Django 3.1.6 on 2021-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0021_auto_20210221_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='post_action',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
