# Generated by Django 3.1.7 on 2021-03-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0022_feature_post_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterfeature',
            options={'default_permissions': (), 'ordering': ['character', 'feature__content_type', 'feature__source_id', 'feature__name'], 'verbose_name': 'Особенность персонажа', 'verbose_name_plural': 'Особенности персонажей'},
        ),
    ]
