# Generated by Django 3.1.7 on 2021-03-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0023_auto_20210308_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills_proficiency',
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.BooleanField(default=False)),
                ('competence', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', related_query_name='skill', to='dnd5e.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dnd5e.skill')),
            ],
            options={
                'verbose_name': 'Навык персонажа',
                'verbose_name_plural': 'Навыки персонажа',
                'default_permissions': (),
            },
        ),
    ]
