# Generated by Django 3.1.7 on 2021-05-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0025_auto_20210309_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevels',
            name='proficiency_bonus',
        ),
    ]
