# Generated by Django 3.1.7 on 2021-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0026_remove_classlevels_proficiency_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='level_table',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
