# Generated by Django 3.1.7 on 2021-06-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0027_feature_level_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='tools_proficiency',
        ),
        migrations.CreateModel(
            name='CharacterToolProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_proficiency', related_query_name='tool', to='dnd5e.character')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dnd5e.tool')),
            ],
            options={
                'verbose_name': 'Инструменты персонажа',
                'verbose_name_plural': 'Инструменты персонажа',
                'default_permissions': (),
            },
        ),
    ]
