# Generated by Django 3.1.7 on 2021-07-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0028_auto_20210618_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancmentchoice',
            options={'default_permissions': (), 'ordering': ['name'], 'verbose_name': 'Выбор для персонажа', 'verbose_name_plural': 'Выборы для персонажей'},
        ),
        migrations.AlterModelOptions(
            name='classleveladvance',
            options={'default_permissions': (), 'ordering': ['class_level__level'], 'verbose_name': 'Преимущество уровня', 'verbose_name_plural': 'Преимущества уровней'},
        ),
        migrations.RemoveField(
            model_name='advancmentchoice',
            name='oneshoot',
        ),
        migrations.RemoveField(
            model_name='characteradvancmentchoice',
            name='selected',
        ),
    ]
