# Generated by Django 3.2.7 on 2021-11-02 22:41

from django.db import migrations
import dnd5e.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0031_auto_20211103_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hit_dice',
            field=dnd5e.model_fields.DiceField(default='1d4'),
            preserve_default=False,
        ),
    ]
