# Generated by Django 3.2.7 on 2021-11-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0032_class_hit_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdice',
            name='maximum',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
