# Generated by Django 3.2.7 on 2021-11-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0033_characterdice_maximum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdice',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dices', related_query_name='dice', to='dnd5e.character'),
        ),
    ]
