# Generated by Django 3.2.9 on 2021-11-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0034_alter_characterdice_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='orig_name',
        ),
        migrations.RemoveField(
            model_name='race',
            name='stat_bonus',
        ),
        migrations.AddField(
            model_name='race',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', related_query_name='race', to='dnd5e.rulebook', verbose_name='Источник'),
        ),
    ]
