# Generated by Django 3.2.9 on 2021-11-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0035_auto_20211124_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrace',
            name='stat_bonus',
        ),
        migrations.AddField(
            model_name='subrace',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subraces', related_query_name='subrace', to='dnd5e.rulebook', verbose_name='Источник'),
        ),
    ]
