# Generated by Django 3.2.9 on 2021-11-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0036_auto_20211124_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
