# Generated by Django 3.2.7 on 2021-11-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0037_remove_skill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maneuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приёмы',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='character',
            name='known_maneuvers',
            field=models.ManyToManyField(editable=False, related_name='_dnd5e_character_known_maneuvers_+', to='dnd5e.Maneuver', verbose_name='Известные приёмы'),
        ),
    ]
