# Generated by Django 3.2.9 on 2021-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0038_auto_20211128_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='monsters',
            field=models.ManyToManyField(editable=False, related_name='in_adventures', to='dnd5e.Monster'),
        ),
    ]
