# Generated by Django 3.2.9 on 2021-12-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0039_alter_adventure_monsters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='group',
            field=models.CharField(blank=True, choices=[('fight_style', 'Боевой стиль')], max_length=12, verbose_name='Группа умений'),
        ),
    ]
