# Generated by Django 3.2.7 on 2021-12-06 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0040_alter_feature_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', related_query_name='class', to='dnd5e.character')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dnd5e.class', verbose_name='Класс')),
                ('subclass', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dnd5e.subclass', verbose_name='Архетип')),
            ],
            options={
                'verbose_name': 'Класс персонажа',
                'verbose_name_plural': 'Классы персонажа',
                'ordering': ['character', 'level'],
                'default_permissions': (),
                'unique_together': {('character', 'klass')},
            },
        ),
    ]
