# Generated by Django 4.0 on 2021-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0042_remove_character_klass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trap',
            old_name='check',
            new_name='saving_check',
        ),
        migrations.AlterField(
            model_name='adventuremonster',
            name='knowledges',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Knowledge', verbose_name='Знания'),
        ),
        migrations.AlterField(
            model_name='background',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.AdvancmentChoice', verbose_name='Выборы для персонажа'),
        ),
        migrations.AlterField(
            model_name='background',
            name='skills_proficiency',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Skill', verbose_name='Владение навыками'),
        ),
        migrations.AlterField(
            model_name='background',
            name='tools_proficiency',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Tool', verbose_name='Владение инструментами'),
        ),
        migrations.AlterField(
            model_name='character',
            name='known_maneuvers',
            field=models.ManyToManyField(editable=False, related_name='+', to='dnd5e.Maneuver', verbose_name='Известные приёмы'),
        ),
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(editable=False, related_name='+', to='dnd5e.Language', verbose_name='Владение языками'),
        ),
        migrations.AlterField(
            model_name='class',
            name='saving_trows',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Ability', verbose_name='Спассброски'),
        ),
        migrations.AlterField(
            model_name='class',
            name='skills_proficiency',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Skill', verbose_name='Владение навыками'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tools_proficiency',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Tool', verbose_name='Владение инструментами'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Language'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='knows',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.Knowledge', verbose_name='Знание'),
        ),
    ]
