# Generated by Django 4.0 on 2021-12-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0043_rename_check_trap_saving_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'default_permissions': (), 'ordering': ['character', '-level', 'klass__name'], 'verbose_name': 'Класс персонажа', 'verbose_name_plural': 'Классы персонажа'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='subclass',
        ),
    ]
