# Generated by Django 4.0 on 2021-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0044_alter_characterclass_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveSmallIntegerField(unique=True, verbose_name='Порядок сортировки')),
                ('name', models.CharField(max_length=24, verbose_name='Название')),
                ('orig_name', models.CharField(max_length=16, verbose_name='Ориг. название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория доспехов',
                'verbose_name_plural': 'Категории доспехов',
                'ordering': ['order_num'],
                'default_permissions': (),
            },
        ),
    ]
