# Generated by Django 4.0 on 2021-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0045_armorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='armor_proficiency',
            field=models.ManyToManyField(related_name='+', to='dnd5e.ArmorCategory', verbose_name='Владение доспехами'),
        ),
    ]
