# Generated by Django 4.0 on 2021-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0046_class_armor_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='armor_proficiency',
            field=models.ManyToManyField(blank=True, related_name='+', to='dnd5e.ArmorCategory', verbose_name='Владение доспехами'),
        ),
    ]
