# Generated by Django 4.0 on 2021-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0048_character_armor_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
                ('code', models.CharField(max_length=16, verbose_name='Кодовое название')),
            ],
            options={
                'verbose_name': 'Категория оружия',
                'verbose_name_plural': 'Категории оружия',
                'default_permissions': (),
            },
        ),
    ]
