# Generated by Django 4.0 on 2021-12-17 17:55

from django.db import migrations, models
import django.db.models.deletion
import dnd5e.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0049_weaponcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Название')),
                ('code', models.CharField(max_length=16, verbose_name='Кодовое название')),
                ('subtype', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Меч')])),
                ('dmg_type', models.CharField(max_length=12, verbose_name='Тип урона')),
                ('dmg_dice', dnd5e.model_fields.DiceField(verbose_name='Урон')),
                ('cost', dnd5e.model_fields.CostField(blank=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', related_query_name='weapon', to='dnd5e.weaponcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип оружия',
                'verbose_name_plural': 'Типы оружия',
                'default_permissions': (),
            },
        ),
    ]
