# Generated by Django 4.0 on 2021-12-21 22:06

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0050_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='weapon_proficency',
            field=gm2m.fields.GM2MField('dnd5e.WeaponCategory', 'dnd5e.Weapon', through_fields=['gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'], verbose_name='Владение оружием'),
        ),
    ]
