# Generated by Django 4.0 on 2021-12-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0052_character_weapon_proficiency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classlevels',
            unique_together={('class_content_type', 'class_object_id', 'level')},
        ),
    ]
