# Generated by Django 4.0 on 2021-12-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0056_class_weapon_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='armor_proficiency',
        ),
        migrations.CreateModel(
            name='ClassArmorProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_multiclass', models.BooleanField(default=False)),
                ('armor_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd5e.armorcategory')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd5e.class')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
