# Generated by Django 4.0 on 2022-01-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0058_class_armor_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiClassProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiclass_advancments', related_query_name='multiclass_advancment', to='dnd5e.class')),
            ],
            options={
                'verbose_name': 'Умение мультикласса',
                'verbose_name_plural': 'Умения мультикласа',
                'default_permissions': (),
            },
        ),
    ]
