# Generated by Django 4.0 on 2022-01-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0062_remove_characterclass_spell_ability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='spell_ability',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd5e.ability'),
        ),
    ]
