# Generated by Django 4.0 on 2022-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0065_subclass_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='codename',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Кодовое имя'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='codename',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Кодовое имя'),
        ),
    ]
