# Generated by Django 4.0 on 2022-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0066_class_codename_alter_subclass_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spellcasting_rules',
            field=models.CharField(default=None, editable=False, max_length=512, null=True),
        ),
    ]
