# Generated by Django 4.1.5 on 2023-01-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0068_alter_monster_condition_immunity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombatAction',
        ),
    ]
