# Generated by Django 4.1.5 on 2023-01-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0069_delete_combataction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RacialSense',
        ),
    ]
