# Generated by Django 4.1.5 on 2023-01-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0070_delete_racialsense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterspellslot',
            options={'default_permissions': (), 'ordering': ['character_id', 'level', 'spent'], 'verbose_name': 'Слот заклинания', 'verbose_name_plural': 'Слоты заклинаний'},
        ),
    ]
