# Generated by Django 4.1.5 on 2023-01-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd5e', '0071_alter_characterspellslot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='known_spells',
            field=models.ManyToManyField(related_name='+', to='dnd5e.spell', verbose_name='Известные заклинания'),
        ),
    ]
