# Generated by Django 4.1.5 on 2023-01-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0072_character_known_spells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'dnd5e', 'model__in': ['class', 'subclass', 'race', 'subrace', 'background']}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='source_id',
            field=models.PositiveIntegerField(),
        ),
    ]
