# Generated by Django 4.1.5 on 2023-01-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0073_alter_feature_content_type_alter_feature_source_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('name', 'content_type', 'source_id')},
        ),
    ]
