# Generated by Django 4.1.5 on 2023-01-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd5e', '0076_characteradvancmentchoice_reason_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteradvancmentchoice',
            name='reason_content_type',
            field=models.ForeignKey(default=None, editable=False, limit_choices_to={'app_label': 'dnd5e', 'model__in': ['characterclass']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
